### ISSUE TITLE
Can't get the plugin to work correctly

### ISSUE THREAD

**Issue by Schlibib-zz** [rooi/homebridge-foscam#10]
i use a C1 and i get this error when i try to change armed state

[8/8/2016, 5:52:54 PM] [C1 Hallway] { [RequestError: Error: connect ETIMEDOUT 192.168.0.104:88]
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 192.168.0.104:88',
  cause: 
   { [Error: connect ETIMEDOUT 192.168.0.104:88]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.0.104',
     port: 88 },
  error: 
   { [Error: connect ETIMEDOUT 192.168.0.104:88]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.0.104',
     port: 88 },
  options: 
   { rejectUnauthorized: true,
     qs: { usr: 'C1', pwd: 'A123456', cmd: 'getMotionDetectConfig' },
     uri: 'http://192.168.0.104:88/cgi-bin/CGIProxy.fcgi',
     method: 'GET',
     callback: undefined,
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false },
  response: undefined }
[8/8/2016, 5:52:55 PM] [C1 Hallway] { [RequestError: Error: connect ETIMEDOUT 192.168.0.104:88]
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 192.168.0.104:88',
  cause: 
   { [Error: connect ETIMEDOUT 192.168.0.104:88]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.0.104',
     port: 88 },
  error: 
   { [Error: connect ETIMEDOUT 192.168.0.104:88]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '192.168.0.104',
     port: 88 },
  options: 
   { rejectUnauthorized: true,
     qs: { usr: 'C1', pwd: 'A123456', cmd: 'getDevState' },
     uri: 'http://192.168.0.104:88/cgi-bin/CGIProxy.fcgi',
     method: 'GET',
     callback: undefined,
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false },
  response: undefined }
^[[AgetMotionDetectConfig1

**Comment by rooi** [comment]
please try: https://github.com/luisiam/homebridge-foscamcamera
This repo can be considered deprecated
