### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by martinweijers** [rooi/homebridge-foscam#12]
Syntax error
Config contains invalid json  

what am i doing wrong ? my first install please be kind 👍 

  "accessory": Woonkamer,
    "name": Weijers,
    "username": admin,
    "password": ......,
    "host": 192.168.1.210,
    "port": 80,
    "stay": 1,
    "away": 3,
    "night": 2,
    "path": "local path to save snapshots"

**Comment by rooi** [comment]
Hi Martin,

This old plugin is no longer supported. Luisiam has created a better functioning one which can find here:
https://github.com/luisiam/homebridge-foscamcamera

I’m using a fork of this myself which support live streaming in homekit:
https://github.com/echamberlain/homebridge-foscamcamera/tree/ffmpeg

Installation (don’t forget sudo) and configuration should be easy

Roy

**Comment by martinweijers** [comment]
Thanks roy! 

I installed the new plugin but it doesn’t show in homekit ?!? How to ?

**Comment by rooi** [comment]
No problem.
You should install homebridge and any plugins you want to use. See this for more details
https://github.com/nfarina/homebridge/wiki (look for the install pages and you platform)
Then create a configuration file in a directory e.g.: platform_dependent/.homebridge/config.ini
You should be able to run homebridge from the command line or terminal by simply executing: homebridge
Any errors should be shown in the log. If it runs ok you should see a qr code and PIN number which you can use to configure homekit on your iPhone or iPad.
