### ISSUE TITLE
Suggestion: get model/serial using getDevInfo()

### ISSUE THREAD

**Issue by luisiam** [rooi/homebridge-foscam#3]
`getDevInfo()` can return device model and serial number. I suggest to use that for the accessory information which will be better for those with more than 1 cam.

**Comment by rooi** [comment]
Good suggestion! I won't be able to work on this till next month though (after my vacation :)

**Comment by luisiam** [comment]
I did try to implement it myself but asynchronous nature of the call is driving me nuts. I don't know how to update the info after the `getDevInfo()` call is finished.

**Comment by rooi** [comment]
please try: https://github.com/luisiam/homebridge-foscamcamera
This repo can be considered deprecated
