### ISSUE TITLE
FI9826P V2 looses motion detection settings incl. mask and schedule

### ISSUE THREAD

**Issue by ronzelver** [rooi/homebridge-foscam#8]
When I use the MotionDetection on/off switch of the plugin my Foscam FI9826P camera looses all settings of the camera's motion detection settings like record on/off, mask, schedule, etc.?!
I know from previous trials with `http get` statements that you have to include all information in the commandstring otherwise everything will be reset to defaults.
This is the example from the CGI manual:
`/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=16& snapInterval=2&sensitivity=1&triggerInterval=5&schedule0=1024&schedule1 =1024&schedule2=1024&schedule3=1024&schedule4=1024&schedule5=102 4&schedule6=1024&area0=1024&area1=1024&area2=1024&area3=1024&ar ea4=1024&area5=1024&area6=1024&area7=1024&area7=1024&area8=1024 &area9=1024&usr=admin&pwd=`

**Comment by rooi** [comment]
Mmm that's strange. The following lines should assure that the old config is retrieved, changed and set:

```
        // Get current config
        this.getConfig.then(function(newConfig){

            // Change isEnable to requested state
            newConfig.isEnable = enable;
            if(enable) newConfig.linkage = this.conversion[value];

            // Update config with requested state
            this.setConfig(newConfig);
            this.log(this.armState[value]);
            callback(null);
        }.bind(this))
```

Perhaps you can add some console.logs to see what happens with your device? @luisiam and I have seen different behavior for his and mine device (c2).

**Comment by luisiam** [comment]
@ronzelver can you post your `config.json`?

**Comment by ronzelver** [comment]
@luisiam, here is my (partial) `config.json`:

`"accessories": [
    {
        "accessory": "Foscam",
        "name": "HDcam Woonkamer",
        "username": "admin",
        "password": "          ",
        "host": "192.168.1.14",
        "port": "88",
        "stay": "1",
        "away": "3",
        "night": "2",
        "path": "/root/.homebridge/snapshots"
    }`

**Comment by luisiam** [comment]
@ronzelver that's the problem. You should not be using 1, 3, 2 as the config. What do you want to do on each state? I can help you set it up correctly

@rooi I think we need better explanation on the readme lol

**Comment by ronzelver** [comment]
OK, I have working settings now, thanks for your support!
