### ISSUE TITLE
Suggestion: Use HomeBridge API 2.0

### ISSUE THREAD

**Issue by luisiam** [rooi/homebridge-foscam#9]
What do you think =P

**Comment by rooi** [comment]
Sound great! KhaosT indicated that it runs stable right? My C2 is behaving strangely the last time, I'll have to try and fix this first (did a reset today)

**Comment by luisiam** [comment]
I just finished coding one of my plugins to use API 2.0. The ability to change/add/remove dynamically without restarting is really nice. The only problem is that you will need to implement it as a `platform`

**Comment by luisiam** [comment]
Working on the configuration option. It will be more error proof comparing to the current method of editing config.json.

![img_0250](https://cloud.githubusercontent.com/assets/16310467/14479698/231aeae6-00d6-11e6-99d9-8eb0cafde3f8.PNG)
![img_0251](https://cloud.githubusercontent.com/assets/16310467/14479701/263eaffa-00d6-11e6-904c-fa9a58f6cea3.PNG)

**Comment by rooi** [comment]
Look great! :D

**Comment by luisiam** [comment]
I basically finished coding but the camera is not showing up after I add it via the app. Hunting the bug right now

**Comment by rooi** [comment]
Ah, need help?

**Comment by luisiam** [comment]
Actually I figured out. I am testing it now. You can join me lol
https://github.com/luisiam/homebridge-foscam2

I haven't implemented period update and snapshot yet but I implemented model and serial number detection via getDevInfo()

**Comment by rooi** [comment]
I just tried the foscam2 but I cannot get to the config screen shown in your screenshots. Do you know what I'm doing wrong?
When I specify the ip etc I get and error that is probably related to the api detection, but I'll get back to this soon.

What are your plans for the repo by the way? Do you want to leave it as foscam2 on github and npm or do you want to merge it with this one (perhaps adopt it and put it under your name since you did most work)?

**Comment by luisiam** [comment]
What app are you using? Only Hesperus support on the fly config so far.
Do you have the error message? I did make some change to the API detection couple days ago. May be you want to update your version.
I currently have no plan yet. I wanna discuss the plan with you, too. I don't think we should merge with the current one since the config is completely different.

**Comment by rooi** [comment]
Ah, found the sliding switch to get to the configuration just now.

I got the following error after on the fly config: [4/25/2016, 6:14:13 PM] [C2] Failed to retrieve camera information!

After this I cannot find the newly added camera as accessory (other accessories and/or platforms are shown). 

I've added some logs, but I'm not sure what triggers the catch...

c2 config = 
c2 config.result = undefined
c2 retreiving camera info
c2 getDevInfo = [object Object]
c2 info.productName = C2
c2 info.serialNo = 1
c2 info.firmwareVer = 2.72.1.18
c2 info.hardwareVer = 1.11.1.6
c2 info.productName.toString() = C2
c2 info.serialNo.toString() = 1
c2 info.firmwareVer.toString() = 2.72.1.18
c2 info.hardwareVer.toString() = 1.11.1.6
[4/25/2016, 7:04:53 PM] [C2] Failed to retrieve camera information!

Perhaps the callback is not called correctly? I'll look further into this tomorrow. Hopefully we can get it working, I would like to use this project as a template to implement the on the fly config in my lightwaverf plugin to support new devices. 

About the merge, do you think a merge with two version is acceptable? Something like v0.1.x is the old one. And v0.2.x is the new one. npm install works with version right?

**Comment by luisiam** [comment]
That's weird. I don't have a C2 and it works on my FI9826W and FI9821W V2. May be the `getDevInfo` works a little differently on the C2? Looks like it's catching an error on the function but it can retrieve the camera info correctly. Can you log the `error` itself and see what's going on? Thanks.

For the merge, I believe most of the users will just use `npm install -g homebridge-foscam`. That will install the latest version automatically, i.e. the one with new API, and it will cause problem without editing the config.json. We can think about this later. Let's fix the bug first lol

**Comment by rooi** [comment]
The error is: ReferenceError: foscamAPI is not defined

Do you have any clue why this occurs? The callback seems valid as well as everything else I print to the console and is obtained from the get functions

**Comment by luisiam** [comment]
I am assuming that you are using the latest version, right?

**Comment by rooi** [comment]
Jep, just checked again to be sure: 9ee6a78bf0dadca8e38629188d1ea3a72ca6732e

**Comment by luisiam** [comment]
I made some minor change. Please try the following version
6a325dcf07fa7e98be2f943b6f72cc14b1cb9b44

**Comment by rooi** [comment]
I've tested your new version, but a similar problem occurred (but the next catch). So investigated further and apparently the catch is triggered by these lines:

  accessory
    .getService(Service.SecuritySystem)
    .getCharacteristic(Characteristic.SecuritySystemCurrentState)
    .getValue();

Before the getValue everything goes well and is defined. Still the getValue triggers the error. Any ideas why?

**Comment by luisiam** [comment]
I am assuming the previous bug is fixed then?

I am not sure if the previous failure mess up the cache already. Try to stop homebridge, delete `~/.homebridge/accessories/cacheAccessories` and restart homebridge. Remember to delete the file after you have stopped homebridge since homebridge will create the file on exit.

**Comment by rooi** [comment]
I think it originated from the same problem. The catch was probably triggered in the same or similar section. Do you want me to double check this?

**Comment by luisiam** [comment]
I can duplicate the issue on my side. Give me some time to debug =]

**Comment by luisiam** [comment]
Fixed. Please remove the `cacheAccessories` and install the latest version.
451df4ed2249ae87515ace77f7365f06504537c0

**Comment by rooi** [comment]
please try: https://github.com/luisiam/homebridge-foscamcamera
This repo can be considered deprecated
